import type { Puzzle } from "./types";

export const PUZZLES: Puzzle[] = [
  {
    id: 1,
    prompt: "Rank from shortest to tallest",
    promptEmoji: "📏",
    shareLabel: "by height",
    metric: "Height (metres)",
    difficulty: "easy",
    items: [
      { name: "House cat",        emoji: "🐱", value: 0.25,  fact: "~25 cm" },
      { name: "Golden Gate Bridge", emoji: "🌉", value: 227,  fact: "227 m tall" },
      { name: "Basketball player", emoji: "🏀", value: 2.1,  fact: "~2.1 m" },
      { name: "Giraffe",          emoji: "🦒", value: 5.5,   fact: "~5.5 m" },
      { name: "Eiffel Tower",     emoji: "🗼", value: 330,   fact: "330 m" },
    ],
  },
  {
    id: 2,
    prompt: "Rank from lightest to heaviest",
    promptEmoji: "⚖️",
    shareLabel: "by weight",
    metric: "Weight (kg)",
    difficulty: "medium",
    items: [
      { name: "iPhone 15",        emoji: "📱", value: 0.171, fact: "171 g" },
      { name: "Labrador dog",     emoji: "🐕", value: 32,    fact: "~32 kg" },
      { name: "Grand piano",      emoji: "🎹", value: 480,   fact: "~480 kg" },
      { name: "African elephant", emoji: "🐘", value: 6000,  fact: "~6 000 kg" },
      { name: "Blue whale",       emoji: "🐋", value: 150000,fact: "~150 000 kg" },
    ],
  },
  {
    id: 3,
    prompt: "Rank from slowest to fastest",
    promptEmoji: "💨",
    shareLabel: "by speed",
    metric: "Top speed (km/h)",
    difficulty: "medium",
    items: [
      { name: "Garden snail",     emoji: "🐌", value: 0.05,  fact: "0.05 km/h" },
      { name: "Human sprint",     emoji: "🏃", value: 44.7,  fact: "44.7 km/h" },
      { name: "Cheetah",         emoji: "🐆", value: 112,   fact: "112 km/h" },
      { name: "Formula 1 car",   emoji: "🏎️", value: 372,   fact: "372 km/h" },
      { name: "SR-71 Blackbird",  emoji: "✈️", value: 3540,  fact: "3 540 km/h" },
    ],
  },
  {
    id: 4,
    prompt: "Rank from oldest to newest",
    promptEmoji: "📅",
    shareLabel: "by release year",
    metric: "Year first released / created",
    difficulty: "medium",
    items: [
      { name: "The printing press", emoji: "🖨️", value: 1440, fact: "~1440 AD" },
      { name: "Telephone",          emoji: "☎️",  value: 1876, fact: "1876" },
      { name: "Television",         emoji: "📺",  value: 1927, fact: "1927" },
      { name: "The internet",       emoji: "🌐",  value: 1983, fact: "1983" },
      { name: "iPhone",             emoji: "📱",  value: 2007, fact: "2007" },
    ],
  },
  {
    id: 5,
    prompt: "Rank from smallest to largest population",
    promptEmoji: "🌍",
    shareLabel: "by population",
    metric: "Population (millions)",
    difficulty: "hard",
    items: [
      { name: "New Zealand",  emoji: "🇳🇿", value: 5.1,    fact: "5.1 million" },
      { name: "Australia",    emoji: "🇦🇺", value: 26.5,   fact: "26.5 million" },
      { name: "United Kingdom", emoji: "🇬🇧", value: 67.7, fact: "67.7 million" },
      { name: "Brazil",       emoji: "🇧🇷", value: 215,    fact: "215 million" },
      { name: "India",        emoji: "🇮🇳", value: 1420,   fact: "1.42 billion" },
    ],
  },
  {
    id: 6,
    prompt: "Rank from cheapest to most expensive",
    promptEmoji: "💸",
    shareLabel: "by price",
    metric: "Approximate price (USD)",
    difficulty: "hard",
    items: [
      { name: "A can of Coke",   emoji: "🥤", value: 1.5,       fact: "~$1.50" },
      { name: "AirPods Pro",     emoji: "🎧", value: 249,        fact: "~$249" },
      { name: "MacBook Pro",     emoji: "💻", value: 2499,       fact: "~$2 499" },
      { name: "Tesla Model S",   emoji: "🚗", value: 89990,      fact: "~$89 990" },
      { name: "Private jet",     emoji: "✈️", value: 50000000,   fact: "~$50 million" },
    ],
  },
  {
    id: 7,
    prompt: "Rank from shortest to longest",
    promptEmoji: "📐",
    shareLabel: "by length",
    metric: "Length (km)",
    difficulty: "hard",
    items: [
      { name: "Brooklyn Bridge",  emoji: "🌉", value: 1.83,   fact: "1.83 km" },
      { name: "English Channel",  emoji: "🌊", value: 560,    fact: "560 km wide" },
      { name: "Great Wall of China", emoji: "🏯", value: 21196, fact: "21 196 km" },
      { name: "Amazon River",     emoji: "🏞️", value: 6992,  fact: "6 992 km" },
      { name: "Equator",          emoji: "🌍", value: 40075,  fact: "40 075 km" },
    ],
  },
  {
    id: 8,
    prompt: "Rank from least to most calories",
    promptEmoji: "🍽️",
    shareLabel: "by calories",
    metric: "Calories per 100 g",
    difficulty: "medium",
    items: [
      { name: "Cucumber",      emoji: "🥒", value: 15,  fact: "15 kcal" },
      { name: "Apple",         emoji: "🍎", value: 52,  fact: "52 kcal" },
      { name: "Boiled egg",    emoji: "🥚", value: 155, fact: "155 kcal" },
      { name: "Cheddar cheese",emoji: "🧀", value: 403, fact: "403 kcal" },
      { name: "Butter",        emoji: "🧈", value: 717, fact: "717 kcal" },
    ],
  },
  {
    id: 9,
    prompt: "Rank from coldest to hottest",
    promptEmoji: "🌡️",
    shareLabel: "by temperature",
    metric: "Average temperature (°C)",
    difficulty: "easy",
    items: [
      { name: "Antarctica (winter)", emoji: "🧊", value: -60, fact: "−60 °C avg" },
      { name: "Siberia (winter)",    emoji: "❄️", value: -25, fact: "−25 °C avg" },
      { name: "London (summer)",     emoji: "☁️", value: 19,  fact: "~19 °C avg" },
      { name: "Sahara Desert",       emoji: "🏜️", value: 38,  fact: "~38 °C avg" },
      { name: "Surface of Venus",    emoji: "🪐", value: 465, fact: "465 °C" },
    ],
  },
  {
    id: 10,
    prompt: "Rank from fewest to most strings",
    promptEmoji: "🎵",
    shareLabel: "by string count",
    metric: "Number of strings",
    difficulty: "easy",
    items: [
      { name: "Bass guitar",    emoji: "🎸", value: 4,   fact: "4 strings" },
      { name: "Violin",         emoji: "🎻", value: 4,   fact: "4 strings" },
      { name: "Classical guitar", emoji: "🎸", value: 6, fact: "6 strings" },
      { name: "Mandolin",       emoji: "🪕", value: 8,   fact: "8 strings (4 pairs)" },
      { name: "Grand piano",    emoji: "🎹", value: 230, fact: "~230 strings" },
    ],
  },
  {
    id: 11,
    prompt: "Rank from lowest to highest altitude",
    promptEmoji: "🏔️",
    shareLabel: "by altitude",
    metric: "Altitude (metres above sea level)",
    difficulty: "medium",
    items: [
      { name: "Dead Sea",      emoji: "🌊", value: -430, fact: "−430 m" },
      { name: "Amsterdam",     emoji: "🇳🇱", value: -2,  fact: "−2 m" },
      { name: "London",        emoji: "🇬🇧", value: 11,  fact: "~11 m" },
      { name: "Mexico City",   emoji: "🇲🇽", value: 2240,fact: "2 240 m" },
      { name: "Mount Everest", emoji: "⛰️", value: 8849, fact: "8 849 m" },
    ],
  },
  {
    id: 12,
    prompt: "Rank from fewest to most Oscar wins",
    promptEmoji: "🏆",
    shareLabel: "by Oscar wins",
    metric: "Academy Awards won (all-time)",
    difficulty: "hard",
    items: [
      { name: "The Dark Knight",   emoji: "🦇", value: 2,  fact: "2 Oscars" },
      { name: "Titanic",           emoji: "🚢", value: 11, fact: "11 Oscars" },
      { name: "Ben-Hur",           emoji: "🏛️", value: 11, fact: "11 Oscars" },
      { name: "La La Land",        emoji: "🎬", value: 6,  fact: "6 Oscars" },
      { name: "The Lord of the Rings: RotK", emoji: "💍", value: 11, fact: "11 Oscars" },
    ],
  },
  {
    id: 13,
    prompt: "Rank from youngest to oldest species",
    promptEmoji: "🦕",
    shareLabel: "by species age",
    metric: "Approximate age of species (million years)",
    difficulty: "hard",
    items: [
      { name: "Modern humans", emoji: "👤", value: 0.3,  fact: "~300 000 years" },
      { name: "Domestic dog",  emoji: "🐕", value: 0.015,fact: "~15 000 years" },
      { name: "Great white shark", emoji: "🦈", value: 16, fact: "~16 million years" },
      { name: "Horseshoe crab", emoji: "🦀", value: 450, fact: "~450 million years" },
      { name: "Coelacanth",    emoji: "🐟", value: 400,  fact: "~400 million years" },
    ],
  },
  {
    id: 14,
    prompt: "Rank from shortest to longest reign",
    promptEmoji: "👑",
    shareLabel: "by reign length",
    metric: "Length of reign (years)",
    difficulty: "hard",
    items: [
      { name: "King Louis XIX",     emoji: "👑", value: 0.000038, fact: "~20 minutes!" },
      { name: "Napoleon Bonaparte", emoji: "⚔️", value: 10,      fact: "~10 years" },
      { name: "Queen Victoria",     emoji: "🏰", value: 63,       fact: "63 years" },
      { name: "King Louis XIV",     emoji: "🌞", value: 72,       fact: "72 years" },
      { name: "Queen Elizabeth II", emoji: "💂", value: 70,       fact: "70 years" },
    ],
  },
  {
    id: 15,
    prompt: "Rank from fewest to most legs",
    promptEmoji: "🦵",
    shareLabel: "by leg count",
    metric: "Number of legs",
    difficulty: "easy",
    items: [
      { name: "Snake",         emoji: "🐍", value: 0,   fact: "0 legs" },
      { name: "Flamingo",      emoji: "🦩", value: 2,   fact: "2 legs" },
      { name: "Spider",        emoji: "🕷️", value: 8,   fact: "8 legs" },
      { name: "Crab",          emoji: "🦀", value: 10,  fact: "10 legs" },
      { name: "Millipede",     emoji: "🐛", value: 750, fact: "up to 750 legs" },
    ],
  },
  {
    id: 16,
    prompt: "Rank from shortest to longest gestation",
    promptEmoji: "🐣",
    shareLabel: "by gestation period",
    metric: "Gestation / incubation period (days)",
    difficulty: "medium",
    items: [
      { name: "Hamster",        emoji: "🐹", value: 16,  fact: "16 days" },
      { name: "Domestic cat",   emoji: "🐱", value: 65,  fact: "~65 days" },
      { name: "Human",          emoji: "👶", value: 280, fact: "~280 days" },
      { name: "Giraffe",        emoji: "🦒", value: 460, fact: "~460 days" },
      { name: "African elephant",emoji: "🐘", value: 660,fact: "~660 days" },
    ],
  },
];

export function getRandomPuzzle(excludeId?: number): Puzzle {
  const pool = excludeId !== undefined
    ? PUZZLES.filter((p) => p.id !== excludeId)
    : PUZZLES;
  return pool[Math.floor(Math.random() * pool.length)];
}